-- CREATE_TABLES.sql
CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORIES (
	CATEGORY_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (CATEGORY_NAME)
);

CREATE TABLE IF NOT EXISTS PRODUCTS (
	PRODUCT_ID SERIAL,
	PRODUCT_NAME VARCHAR(20) NOT NULL,
	PRODUCT_COST NUMERIC NOT NULL,
	CATEGORY_NAME VARCHAR(20) NOT NULL,
	PRIMARY KEY (PRODUCT_ID),
	FOREIGN KEY (CATEGORY_NAME) REFERENCES PRODUCT_CATEGORIES(CATEGORY_NAME)
);

CREATE TABLE IF NOT EXISTS PRODUCT_ORDERS (
	ORDER_ID SERIAL NOT NULL,
	PRODUCT_ID SERIAL NOT NULL,
	PRODUCT_AMOUNT INTEGER NOT NULL,
	ORDER_DOS DATE NOT NULL,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TYPE RECEIPT_STATE AS ENUM (
	'ACTIVE', 'CANCELLED', 'PAID'
);

CREATE TABLE IF NOT EXISTS CASHIERS (
	CASHIER_ID SERIAL NOT NULL,
	CASHIER_NAME VARCHAR(25) NOT NULL,
	PRIMARY KEY (CASHIER_ID)
);

CREATE TABLE RECEIPTS (
	RECEIPT_ID SERIAL NOT NULL,
	RECEIPT_DOS DATE NOT NULL,
	RECEIPT_TOTAL NUMERIC NOT NULL,
	RECEIPT_STATE RECEIPT_STATE NOT NULL,
	CASHIER_ID SERIAL NOT NULL,
	PRIMARY KEY (RECEIPT_ID),
	FOREIGN KEY (CASHIER_ID) REFERENCES CASHIERS(CASHIER_ID)
);