-- DROP_TABLES.sql
DROP TABLE IF EXISTS CASHIERS CASCADE;
DROP TABLE IF EXISTS PRODUCTS CASCADE;
DROP TABLE IF EXISTS PRODUCT_CATEGORIES;
DROP TABLE IF EXISTS PRODUCT_ORDERS CASCADE;
DROP TABLE IF EXISTS RECEIPTS CASCADE;
DROP TYPE IF EXISTS RECEIPT_STATE CASCADE;